spring:

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: "jdbc:mysql://newslettercollector-db.cto5vei4nbnz.ap-northeast-2.rds.amazonaws.com:3306/study"
    username: admin

  jpa:
    properties:
      hibernate:
        show_sql: true

  profiles:
    include: secret


